name: CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: liamnou
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace image:... in compose.yaml with value of file latest_tag.txt
        run: |
          sed -i "s|image:.*|image: $(cat latest_tag.txt)|g" compose.yaml

      - name: Copy file to remote host
        uses: appleboy/scp-action@master
        with:
          host: lestar.ddns.net
          username: lestar
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: .env
          target: /home/lestar/containers/${{ env.IMAGE_NAME }}

      - name: Execute command over SSH
        uses: appleboy/ssh-action@master
        with:
          host: lestar.ddns.net
          username: lestar
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/lestar/containers/${{ env.IMAGE_NAME }}
            dotenvx decrypt .env

      - name: Deploy compose
        uses: sulthonzh/docker-remote-deployment-action@v0.1.2-beta
        with:
          remote_docker_host: lestar@lestar.ddns.net
          remote_docker_port: ${{ secrets.PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          copy_stack_file: true
          deploy_path: /home/lestar/containers/${{ env.IMAGE_NAME }}
          stack_file_name: compose.yaml
          keep_files: 5
          args: up -d --remove-orphans
          docker_registry_username: ${{ env.REGISTRY }}
          docker_registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
